// Code generated by bpf2go; DO NOT EDIT.

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type NatNatEntry struct {
	_              structs.HostLayout
	TranslatedIp   uint32
	TranslatedPort uint16
	_              [2]byte
	LastSeen       uint64
}

type NatNatKey struct {
	_        structs.HostLayout
	SrcIp    uint32
	DstIp    uint32
	SrcPort  uint16
	DstPort  uint16
	Protocol uint8
	_        [3]byte
}

// LoadNat returns the embedded CollectionSpec for Nat.
func LoadNat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NatBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Nat: %w", err)
	}

	return spec, err
}

// LoadNatObjects loads Nat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NatObjects
//	*NatPrograms
//	*NatMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNatObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NatSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NatSpecs struct {
	NatProgramSpecs
	NatMapSpecs
	NatVariableSpecs
}

// NatProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NatProgramSpecs struct {
	TcNatProg *ebpf.ProgramSpec `ebpf:"tc_nat_prog"`
}

// NatMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NatMapSpecs struct {
	ConntrackMap *ebpf.MapSpec `ebpf:"conntrack_map"`
}

// NatVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NatVariableSpecs struct {
}

// NatObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNatObjects or ebpf.CollectionSpec.LoadAndAssign.
type NatObjects struct {
	NatPrograms
	NatMaps
	NatVariables
}

func (o *NatObjects) Close() error {
	return _NatClose(
		&o.NatPrograms,
		&o.NatMaps,
	)
}

// NatMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNatObjects or ebpf.CollectionSpec.LoadAndAssign.
type NatMaps struct {
	ConntrackMap *ebpf.Map `ebpf:"conntrack_map"`
}

func (m *NatMaps) Close() error {
	return _NatClose(
		m.ConntrackMap,
	)
}

// NatVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNatObjects or ebpf.CollectionSpec.LoadAndAssign.
type NatVariables struct {
}

// NatPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNatObjects or ebpf.CollectionSpec.LoadAndAssign.
type NatPrograms struct {
	TcNatProg *ebpf.Program `ebpf:"tc_nat_prog"`
}

func (p *NatPrograms) Close() error {
	return _NatClose(
		p.TcNatProg,
	)
}

func _NatClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed nat_bpf.o
var _NatBytes []byte
